version: '3'

services:
  anaconda:
    image: ykamoge/anaconda3
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      jupyter notebook --ip 0.0.0.0 --allow-root --no-browse 
      --notebook-dir=./notebooks
      --NotebookApp.token='' --NotebookApp.password=''
    volumes:
      - .:/var/app/
    ports:
      - 8888:8888
    environment:
      TZ: Asia/Tokyo

